apiVersion: v1
kind: Namespace
metadata:
  name: infrastructure
  labels:
    name: infrastructure
    purpose: monitoring-and-infrastructure
---
apiVersion: v1
kind: Namespace
metadata:
  name: applications
  labels:
    name: applications
    purpose: user-applications